### ISSUE TITLE
documentation router invocation error

### ISSUE THREAD

**Issue by yogeshVU** [webgme/bindings#7]
In the Getting started readme:

When trying to execute the
```
webgme import router BindingsDocs webgme-bindings
```
One get's following error

```
vagrant@linux:~/webgme-tut/MyNewProject$ webgme import router BindingDocs webgme-bindings
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mynewproject@1.0.0 No repository field.
npm WARN mynewproject@1.0.0 No license field.

+ webgme-bindings@1.2.0
updated 1 package in 3.857s
/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:255
        componentPath = utils.getPathContaining(otherConfig[this._webgmeName].basePaths.map(
                                                                              ^

TypeError: Cannot read property 'basePaths' of undefined
    at RouterManager.ComponentManager._getPathFromGME (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:255:79)
    at RouterManager.ComponentManager._getPathFromDependency (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:222:73)
    at RouterManager.ComponentManager._getJsonForConfig (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:184:10)
    at RouterManager._getJsonForConfig (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/RouterManager.js:111:50)
    at RouterManager.ComponentManager._addComponentFromProject (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:164:17)
    at utils.installProject (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/ComponentManager.js:153:18)
    at ChildProcess.job.on.code (/home/vagrant/.nvm/versions/node/v8.9.0/lib/node_modules/webgme-cli/src/utils.js:443:20)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)

```

**Comment by brollb** [comment]
This actually looks like a bug in http://github.com/webgme/webgme-cli :)

**Comment by brollb** [comment]
It looks like there was a typo in your import command. Can you try:
```
webgme import router BindingsDocs webgme-bindings
```
(It looks like you accidentally tried to import "BindingDocs" in the one with the error.)

**Comment by brollb** [comment]
@yogeshVU - Does the above command work (using "BindingsDocs" rather than "BindingDocs")?

**Comment by kecso** [comment]
I can confirm it works.

**Comment by yogeshVU** [comment]
@brollb : somehow I missed this issue and was following on the webgme-cli repo. 
Yes using the above new command I am able to access the docs at `/bindings-docs/python/index.html`
Good to close

**Comment by brollb** [comment]
Great - thanks!
